/* =====================================================================
   deal_dashboard_data_v1.js
   GENERATED FILE — do not edit by hand.
   Produced by refresh_deal_dashboard_data_v1.py from the approved
   deal-json blocks in deal_command_center_v1.md (the source of truth).
   If this file and the Command Center disagree, the Command Center wins.
===================================================================== */
window.DEAL_DASHBOARD_DATA = {
  "meta": {
    "source_file": "deal_command_center_v1.md",
    "generated_at": "2026-06-04",
    "command_center_as_of": "2026-06-05",
    "record_count": 3,
    "stale_days": 7,
    "excluded_fields_notice": "Commercial detail is INTERNAL-ONLY and contained within each deal's commercial_context. It is SE context, not customer-facing positioning, and commercial promises are not asserted outside commercial_context. The Command Center Markdown is the source of truth; do not edit this generated data directly.",
    "governance_notice": "Generated from approved deal-json blocks in deal_command_center_v1.md. Command Center is the source of truth; if they disagree, the Command Center wins. Do not edit this file by hand — re-run refresh_deal_dashboard_data_v1.py."
  },
  "attention": [
    {
      "deal": "Fontainebleau Las Vegas",
      "whyNow": "June 9 stakeholder demo with Aislinn, the confirmed decision maker — her first exposure and the highest-stakes moment in the deal.",
      "outcome": "Convert Aislinn from evaluator to sponsor / decision driver.",
      "openQuestion": "Who owns the spend decision (economic buyer), and what is the decision process?",
      "owner": "Kris / AE",
      "date": "2026-06-09"
    },
    {
      "deal": "Marvin",
      "whyNow": "Confirmed June 8 (2pm CT) stakeholder + technical deep-dive against a hard Dec 18-19 GetFeedback sunset.",
      "outcome": "Win vs consolidating onto the SurveyMonkey Enterprise they already own; prove integration + low-disruption migration; land the two dealer surveys.",
      "openQuestion": "Is the mutual NDA executed, and who is the economic buyer / spend sign-off owner?",
      "owner": "Kris / Trent",
      "date": "2026-06-08"
    },
    {
      "deal": "McAfee",
      "whyNow": "Large multi-vendor RFP gone quiet — stale 16 days against a coming-weeks procurement clock, with follow-up materials owed and no next session booked.",
      "outcome": "Re-establish position: submit the procurement-portal package, lock a next session with Marina, identify the economic buyer + eval criteria, and fix the demo environment.",
      "openQuestion": "Who owns the spend decision, what are the formal scoring criteria, and was the portal package submitted?",
      "owner": "Deshik / Kris",
      "date": "this week"
    }
  ],
  "deals": [
    {
      "id": "fontainebleau-las-vegas",
      "name": "Fontainebleau Las Vegas",
      "industry": "Hospitality",
      "vertical": "Hospitality / casino resort, Las Vegas",
      "stage": "Post-first demo; stakeholder demo scheduled for June 9",
      "nextMeeting": {
        "date": "Jun 9",
        "iso": "2026-06-09",
        "title": "Stakeholder demo",
        "sub": "with Aislinn, Director of Guest Experience"
      },
      "meddpiccSummary": "2/8",
      "weak": "Decision process / economic buyer",
      "competitor": "Medallia (via ComOps reseller)",
      "competitorTags": [
        "Medallia",
        "ComOps"
      ],
      "decisionMaker": {
        "text": "Aislinn, Director of Guest Experience — Confirmed",
        "status": "green"
      },
      "economicBuyer": "Unknown",
      "metrics": "300K sends/yr · ~45K responses/yr (~15% RR) · ~150K historical responses to migrate",
      "identifiedPain": "Medallia delivered via the ComOps reseller and the renewal prompted re-evaluation; wants the right long-term, self-service solution; preserve historical reporting continuity; match current functionality; integrate with existing stack; reporting; follow-up on negative scores.",
      "nextAction": {
        "text": "Prepare the June 9 stakeholder demo for Aislinn. Focus: Medallia-via-ComOps displacement; historical reporting continuity; 150K historical response migration; 300K/45K scale; API + scheduled data feed readiness; dashboard parity + executive reporting (security/compliance is Step 2 after the demo).",
        "owner": "Kris / AE",
        "date": "2026-06-09"
      },
      "lastTouch": "2026-06-01",
      "confidence": "Facts + Aislinn-as-decision-maker + June 9 schedule = Confirmed; economic buyer / procurement / security = Unknown.",
      "meddpicc": {
        "Metrics": "amber",
        "Economic buyer": "amber",
        "Decision criteria": "amber",
        "Decision process": "grey",
        "Paper process": "amber",
        "Identified pain": "green",
        "Champion": "amber",
        "Competition": "green"
      },
      "meddpiccNotes": {
        "Metrics": "Volume known (300K/45K/150K); no business-outcome target.",
        "Economic buyer": "Decision maker (Aislinn) confirmed; spend authority unknown.",
        "Decision criteria": "Continuity, functionality parity, integration known; not formally weighted.",
        "Decision process": "No documented path to signature.",
        "Paper process": "Security/compliance review required (Step 2); rest undefined.",
        "Identified pain": "Senior and clear: ComOps dependency + continuity + reporting.",
        "Champion": "Beck active; influence with the decision maker unproven.",
        "Competition": "Medallia via ComOps clearly identified; displacement underway."
      },
      "committee": [
        {
          "name": "Aislinn",
          "role": "Director of Guest Experience · Decision maker",
          "status": "green",
          "statusText": "Confirmed"
        },
        {
          "name": "Beck Sundquist",
          "role": "Exec Director of Product · Champion / coach",
          "status": "amber",
          "statusText": "Active; influence with DM unproven"
        },
        {
          "name": "Beck's data team",
          "role": "API / scheduled data feed review",
          "status": "grey",
          "statusText": "In evaluation"
        },
        {
          "name": "Cybersecurity team",
          "role": "Security / compliance review",
          "status": "grey",
          "statusText": "Step 2 after June 9"
        },
        {
          "name": "Economic buyer",
          "role": "Spend authority",
          "status": "grey",
          "statusText": "Unknown"
        }
      ],
      "risks": {
        "technical": [
          "Security/compliance review not yet started — Step 2 after the June 9 demo."
        ],
        "migration": [
          "~150K historical responses to migrate — continuity is the landmine."
        ],
        "decision": [
          "Decision process undocumented; economic buyer / spend authority unknown.",
          "June 9 is the decision-maker's first exposure."
        ],
        "competition": [
          "Medallia incumbent, supplied via ComOps reseller — like-for-like displacement."
        ]
      },
      "flags": {
        "securityPending": true,
        "migrationRisk": true
      },
      "commercialContext": {
        "internal_only": true,
        "price_sensitivity": "Elevated — the ComOps reseller renewal prompted re-evaluation (prospect signal, not a customer-facing claim).",
        "budget_signal": "Unknown",
        "renewal_or_contract_timing": "Medallia-via-ComOps renewal was the trigger event; exact renewal dates Unknown.",
        "procurement_status": "Unknown; security/compliance review is Step 2 after the June 9 demo.",
        "commercial_risk": "Displacing a tightly-integrated Medallia + ComOps platform-plus-services duo; reseller dependency.",
        "demo_implication": "Lead on self-service control, ownership, reporting continuity and migration confidence; avoid unsupported cost-advantage claims unless the AE confirms.",
        "ae_alignment_needed": true
      }
    },
    {
      "id": "marvin",
      "name": "Marvin",
      "industry": "Building materials",
      "vertical": "Building materials — windows & doors · ~90% dealer/distribution, ~10% DTC",
      "stage": "Demo done; stakeholder + technical deep-dive Jun 8 (2pm CT)",
      "nextMeeting": {
        "date": "Jun 8",
        "iso": "2026-06-08",
        "title": "Stakeholder + technical deep-dive",
        "sub": "2:00 PM CT (= Jun 9, 12:30 AM IST) · Host Trent (AE), SE Kris, Toby Hoskins + Marvin team"
      },
      "meddpiccSummary": "3/8",
      "weak": "Competition (internal SurveyMonkey path)",
      "competitor": "GetFeedback (sunsetting Dec 18-19); SurveyMonkey Enterprise (internal alt)",
      "competitorTags": [
        "GetFeedback",
        "SurveyMonkey Enterprise",
        "Qualtrics"
      ],
      "decisionMaker": {
        "text": "Toby Hoskins — Champion w/ decision authority",
        "status": "green"
      },
      "economicBuyer": "Unknown",
      "metrics": "under 10K responses/yr · 2 surveys (post in-home consult [higher priority]; design-consultant follow-up [lower]) · scope = dealer/distribution only, not DTC · revenue ~90% dealer / ~10% DTC",
      "identifiedPain": "GetFeedback sunsetting Dec 18-19, 2026 (the drop-dead date); needs low-disruption migration; maintain set-and-forget surveys; keep Salesforce-triggered workflow + Marketing Cloud distribution via API; replicate GetFeedback branching logic on Salesforce data.",
      "nextAction": {
        "text": "Prep/run the Jun 8 session. Prove Salesforce API trigger + Marketing Cloud distribution + replicate GetFeedback branching; out-frame consolidating onto SurveyMonkey; confirm NDA executed before deep API config; surface the economic buyer + lock decision/timeline to beat the Dec 18-19 sunset.",
        "owner": "Kris / Trent",
        "date": "2026-06-08"
      },
      "lastTouch": "2026-05-29",
      "confidence": "Facts Confirmed (call transcript + email + invite); economic buyer / NDA-execution = Unknown.",
      "meddpicc": {
        "Metrics": "amber",
        "Economic buyer": "amber",
        "Decision criteria": "green",
        "Decision process": "amber",
        "Paper process": "amber",
        "Identified pain": "green",
        "Champion": "green",
        "Competition": "amber"
      },
      "meddpiccNotes": {
        "Metrics": "Volume known; no outcome target.",
        "Economic buyer": "Toby has decision authority; spend sign-off unconfirmed.",
        "Decision criteria": "Clear and SurveySparrow-confirmed fit.",
        "Decision process": "Decision within ~1 month; go-live targeting September.",
        "Paper process": "Mutual NDA in review (Varshini).",
        "Identified pain": "Hard sunset compelling event.",
        "Champion": "Toby driving NDA + scheduling + has decision authority.",
        "Competition": "SurveyMonkey Enterprise internal alternative already owned."
      },
      "committee": [
        {
          "name": "Toby Hoskins",
          "role": "Manager, Digital Technology · Champion w/ decision authority",
          "status": "green",
          "statusText": "Driving NDA + scheduling"
        },
        {
          "name": "Marvin technical team",
          "role": "PM + tech lead · technical validation",
          "status": "grey",
          "statusText": "Joining Jun 8"
        },
        {
          "name": "Trent Ward",
          "role": "Director NA · Account Executive (internal)",
          "status": "grey",
          "statusText": "Host / AE"
        },
        {
          "name": "Varshini Saravanan",
          "role": "NDA review (internal)",
          "status": "grey",
          "statusText": "NDA in review"
        },
        {
          "name": "Economic buyer",
          "role": "Spend sign-off",
          "status": "grey",
          "statusText": "Unknown"
        }
      ],
      "risks": {
        "technical": [
          "Salesforce + Marketing Cloud integration to validate Jun 8.",
          "NDA not yet executed — gates the deep Salesforce API config."
        ],
        "migration": [
          "GetFeedback to SurveySparrow low-disruption migration required.",
          "Parallel-run de-risk before the Dec 18-19 cutover deadline."
        ],
        "decision": [
          "Toby has decision authority; spend sign-off owner unconfirmed.",
          "Wants a decision within ~1 month; go-live targeting September."
        ],
        "competition": [
          "GetFeedback sunsetting (acquisition-driven).",
          "SurveyMonkey Enterprise = internal alternative (real threat; already used by Marvin brand, renews September).",
          "Qualtrics ruled out (complexity)."
        ]
      },
      "flags": {
        "securityPending": false,
        "migrationRisk": true
      },
      "commercialContext": {
        "internal_only": true,
        "price_sensitivity": "Unknown",
        "budget_signal": "Prospect-stated budget preference from raw notes; internal-only context, not AE-approved pricing or a SurveySparrow commitment. Toby Hoskins: \"Ideally, we'd like to keep it under $10,000 a year.\" Internal SE context only. Not customer-facing positioning. Not a pricing commitment. Requires AE alignment.",
        "renewal_or_contract_timing": "GetFeedback incumbent sunsetting Dec 18-19, 2026 — a hard cutover deadline (prospect signal).",
        "procurement_status": "Mutual NDA in review (Varshini); decision sought within ~1 month; go-live targeting September.",
        "commercial_risk": "Consolidation onto the SurveyMonkey Enterprise they already own (renews September) is the path-of-least-resistance threat.",
        "demo_implication": "Lead on low-disruption migration, Salesforce + Marketing Cloud continuity, technical validation, and out-framing the SurveyMonkey consolidation; avoid unsupported cost-advantage claims unless the AE confirms.",
        "ae_alignment_needed": true
      }
    },
    {
      "id": "mcafee",
      "name": "McAfee",
      "industry": "Cybersecurity",
      "vertical": "Cybersecurity / consumer SaaS (US)",
      "stage": "Active RFI/RFP (multi-vendor); 2 demos done; UXR scope dropped; follow-up materials owed",
      "nextMeeting": null,
      "meddpiccSummary": "1/8",
      "weak": "Economic buyer / Competition",
      "competitor": "Multi-vendor RFI/RFP (competitors largely unnamed); Qualtrics + Alida referenced as benchmarks",
      "competitorTags": [
        "Qualtrics",
        "Alida"
      ],
      "decisionMaker": {
        "text": "Not identified (multi-stakeholder RFP)",
        "status": "grey"
      },
      "economicBuyer": "Unknown",
      "metrics": "Large engaged audience (31 invited Call 1 / 12 Call 2) · no customer volumes or decision date surfaced (Unknown)",
      "identifiedPain": "[VOC/CX] GDPR / security & privacy + data anonymization pipeline; no-code complex campaign triggering; advanced AI text analytics; native app integration beyond JavaScript (strict Java restrictions); Adobe custom-event triggering gap. [Market Research] premium-tier feature prioritization via MaxDiff; SPSS (.sav) export; multilingual; panel flexibility (vendor + bring-your-own).",
      "nextAction": {
        "text": "Submit RFP follow-up materials via the procurement portal + re-establish a next session with Marina; deliver GDPR/SDK/security proof (VOC) and a fixed, populated MR demo; identify the economic buyer + formal eval criteria.",
        "owner": "Deshik / Kris",
        "date": "this week"
      },
      "lastTouch": "2026-05-20",
      "confidence": "Facts Confirmed (both call notes); economic buyer / timeline / competitor set / portal-submission status = Unknown.",
      "meddpicc": {
        "Metrics": "grey",
        "Economic buyer": "red",
        "Decision criteria": "amber",
        "Decision process": "amber",
        "Paper process": "amber",
        "Identified pain": "green",
        "Champion": "amber",
        "Competition": "red"
      },
      "meddpiccNotes": {
        "Metrics": "No customer metrics/volumes/targets surfaced.",
        "Economic buyer": "Not identified; Marina is sourcing/procurement, not spend owner.",
        "Decision criteria": "Themes clear; formal RFP scoring unknown.",
        "Decision process": "Formal RFI/RFP, multi-stakeholder, coming-weeks.",
        "Paper process": "Procurement portal + mandatory security/infosec review known.",
        "Identified pain": "Clear, multiple, senior across both tracks.",
        "Champion": "Marina engaged on process; no champion with decision power.",
        "Competition": "Contested multi-vendor RFP; UXR half already lost."
      },
      "committee": [
        {
          "name": "Marina Mikhaleva",
          "role": "Global Strategic Sourcing Manager · process champion",
          "status": "amber",
          "statusText": "Sourcing/procurement, not economic buyer"
        },
        {
          "name": "Carolina Thomsen",
          "role": "VOC · primary CX technical evaluator",
          "status": "amber",
          "statusText": "Left Call 1 early; concerns unaddressed"
        },
        {
          "name": "Kara Kalivoda",
          "role": "Global Director, VOC Insights & Analytics",
          "status": "grey",
          "statusText": "Senior stakeholder"
        },
        {
          "name": "Tiffanie Williams",
          "role": "Director, Market Intelligence · MR influencer",
          "status": "grey",
          "statusText": "Engaged on MaxDiff"
        },
        {
          "name": "Engineering / security",
          "role": "Sridhar Matta, Shuborno Biswas, Sachin Jadhav · SDK / Java / security",
          "status": "grey",
          "statusText": "Technical validation"
        },
        {
          "name": "Compliance / infosec",
          "role": "Security & compliance review",
          "status": "grey",
          "statusText": "Heavily involved gatekeepers"
        },
        {
          "name": "Economic buyer",
          "role": "Spend authority",
          "status": "grey",
          "statusText": "Unknown"
        }
      ],
      "risks": {
        "technical": [
          "GDPR / security & privacy + data anonymization pipeline — must prove.",
          "SDK integration + whitelisting/firewall requirements.",
          "Native app integration beyond JavaScript (strict Java restrictions on assets/form factors).",
          "Verify-with-product: CogniView three-level taxonomy timeline; multilingual report generation (English-only today); SPSS export timeline."
        ],
        "migration": [],
        "decision": [
          "Economic buyer unidentified in a late-stage RFP.",
          "Formal eval criteria / scoring unknown; multi-stakeholder (eng, compliance, CX, MR).",
          "Aggressive coming-weeks procurement clock; no next session booked."
        ],
        "competition": [
          "Contested multi-vendor RFP (competitors largely unnamed).",
          "UXR scope lost (~50% of MR) to capability gaps — risk a rival bundles UXR + consumer insights.",
          "Qualtrics + Alida referenced as benchmarks."
        ]
      },
      "flags": {
        "securityPending": true,
        "migrationRisk": false
      },
      "commercialContext": {
        "internal_only": true,
        "price_sensitivity": "Unknown",
        "budget_signal": "Unknown — no budget was discussed despite the late-stage RFI/RFP.",
        "renewal_or_contract_timing": "Unknown",
        "procurement_status": "Active multi-vendor RFI/RFP via the procurement portal; coming-weeks vendor-response clock; mandatory security/infosec review.",
        "commercial_risk": "Contested multi-vendor RFP; UXR scope already lost (~50% of MR) to capability gaps.",
        "demo_implication": "Re-establish position fast: submit portal materials, identify the economic buyer + eval criteria, prove GDPR/SDK/security. Two-best-in-class positioning is at risk if a rival bundles UXR + consumer insights.",
        "ae_alignment_needed": true
      }
    }
  ]
};
