#!/usr/bin/env python3
"""
refresh_deal_dashboard_data_v1.py
=================================
Validator + regenerator for the SE Deal Cockpit data mirror.

WHAT IT DOES
  - Reads ONLY the ```deal-json fenced blocks inside deal_command_center_v1.md.
  - NEVER parses the free-form Markdown deal cards (no brittle prose parsing).
  - Validates every block (fail-closed: writes nothing if any check fails).
  - On success, regenerates deal_dashboard_data_v1.js in the shape that
    deal_dashboard_v2.html expects (window.DEAL_DASHBOARD_DATA = {...}).

SOURCE OF TRUTH
  deal_command_center_v1.md is canonical. This script only mirrors its
  fenced blocks into JS. If they ever disagree, the Command Center wins —
  so re-run this AFTER an approved Command Center edit, never the reverse.

SAFETY
  - No raw-note ingestion, no network, no folder watching, no server.
  - Commercial fields are forbidden anywhere except the policy notice keys.
  - If anything is missing/inconsistent/low-confidence, it STOPS and reports.
"""

import json
import os
import re
import sys
from datetime import datetime, date

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE_MD = os.path.join(HERE, "deal_command_center_v1.md")
OUTPUT_JS = os.path.join(HERE, "deal_dashboard_data_v1.js")

# Date stamps are set DYNAMICALLY at run time (no stale hardcoded constants).
#   - generated_at        = the run date, always.
#   - command_center_as_of = the run date by default; a controlled override may be
#     supplied via env var COMMAND_CENTER_AS_OF=YYYY-MM-DD when intentionally
#     regenerating an approved snapshot dated earlier than today.
_RUN_DATE = date.today().isoformat()
GENERATED_AT = _RUN_DATE
_cc_override = os.environ.get("COMMAND_CENTER_AS_OF", "").strip()
if _cc_override:
    try:
        datetime.strptime(_cc_override, "%Y-%m-%d")
        COMMAND_CENTER_AS_OF = _cc_override
    except ValueError:
        print(f"WARNING: ignoring invalid COMMAND_CENTER_AS_OF override {_cc_override!r}; using run date")
        COMMAND_CENTER_AS_OF = _RUN_DATE
else:
    COMMAND_CENTER_AS_OF = _RUN_DATE
STALE_DAYS = 7

EXCLUDED_FIELDS_NOTICE = (
    "Commercial detail is INTERNAL-ONLY and contained within each deal's commercial_context. "
    "It is SE context, not customer-facing positioning, and commercial promises are not asserted "
    "outside commercial_context. The Command Center Markdown is the source of truth; "
    "do not edit this generated data directly."
)
GOVERNANCE_NOTICE = (
    "Generated from approved deal-json blocks in deal_command_center_v1.md. "
    "Command Center is the source of truth; if they disagree, the Command Center wins. "
    "Do not edit this file by hand — re-run refresh_deal_dashboard_data_v1.py."
)

# Keys whose VALUES may legitimately contain commercial vocabulary (they describe the policy).
NOTICE_KEYS = {"excluded_commercial_fields_notice", "excluded_fields_notice", "governance_notice"}

# Commercial-leakage filter (v3 — containment model):
#   Commercial detail is INTERNAL and USEFUL, but must be contained inside each deal's
#   `commercial_context` object. The scanner exempts that subtree (and notice keys).
#   OUTSIDE commercial_context we still block: hard commercial specifics (pricing, ACV,
#   discount, plan tier, contract terms, commercial terms, budget target, annual spend,
#   currency amounts) AND customer-facing commercial PROMISES. Normal qualification
#   language (budget owner, economic buyer, contract expiry, procurement, renewal,
#   commercial context, pricing pressure, spend authority) is allowed everywhere.
ALLOW_PHRASES = [
    "budget owner", "economic buyer", "spend authority", "contract expiry",
    "procurement", "renewal", "commercial context", "pricing pressure",
]
COMMERCIAL_WORDS = ["pricing", "price", "acv", "discount"]
COMMERCIAL_PHRASES = ["plan tier", "contract terms", "commercial terms", "budget target", "annual spend"]
# Customer-facing commercial PROMISES — never allowed outside commercial_context.
PROMISE_PHRASES = [
    "cheaper than", "cheaper", "lower cost", "less than they pay", "less than we pay",
    "savings guarantee", "guaranteed roi", "discount promise", "confirmed price advantage",
]
_CURRENCY_RES = [
    re.compile(r"[\$€£]\s?\d"),
    re.compile(r"\b\d[\d,\.]*\s?(usd|eur|gbp|dollars?|euros?|pounds?)\b", re.IGNORECASE),
]

REQUIRED_TOP = [
    "schema_version", "deal_id", "deal_name", "industry", "vertical", "stage",
    "last_touch", "competitor", "decision_maker", "economic_buyer", "meddpicc",
    "next_best_action", "confidence", "updated_at",
]
MEDD_KEYS = ["metrics", "economic_buyer", "decision_criteria", "decision_process",
             "paper_process", "identified_pain", "champion", "competition"]
MEDD_DISPLAY = {
    "metrics": "Metrics", "economic_buyer": "Economic buyer", "decision_criteria": "Decision criteria",
    "decision_process": "Decision process", "paper_process": "Paper process",
    "identified_pain": "Identified pain", "champion": "Champion", "competition": "Competition",
}
STATUS_COLOR = {"green": "green", "amber": "amber", "red": "red", "unknown": "grey"}

# --- Allowed status enums (compared case-insensitively) -----------------------
MEDD_STATUS = {"green", "amber", "red", "unknown"}
PERSON_STATUS = {"confirmed", "unknown", "assumed", "amber", "green", "red",
                 "in review", "not started", "scheduled", "completed"}
COLOR_STATUS = {"green", "amber", "red", "grey"}            # buying_committee.status / *_color
MEETING_STATUS = {"scheduled", "completed", "tentative", "tbd", "none"}

errors = []


def fail(msg):
    errors.append(msg)


def find_external_violations(text):
    """Commercial terms/promises that are NOT allowed outside commercial_context.
    Allow-listed qualification phrases are stripped first so they never trip."""
    if not text:
        return []
    low = text.lower()
    for ap in ALLOW_PHRASES:
        low = low.replace(ap, " ")
    hits = []
    for w in COMMERCIAL_WORDS:
        if re.search(rf"\b{re.escape(w)}\b", low):
            hits.append(w)
    for ph in COMMERCIAL_PHRASES:
        if ph in low:
            hits.append(ph)
    for ph in PROMISE_PHRASES:
        if ph in low:
            hits.append(ph)
    for rx in _CURRENCY_RES:
        if rx.search(text):
            hits.append("currency amount")
    return hits


CC_KEYS = {"commercial_context", "commercialContext"}


def scan_commercial(node, deal_id, path="", in_cc=False):
    """Recursively scan parsed data. Commercial detail is allowed INSIDE
    commercial_context (the internal containment zone) and inside NOTICE keys;
    elsewhere, commercial specifics and customer-facing promises fail closed."""
    if isinstance(node, dict):
        for k, v in node.items():
            if k in NOTICE_KEYS:
                continue  # policy notices may name commercial fields
            scan_commercial(v, deal_id, path + k + ".", in_cc or k in CC_KEYS)
    elif isinstance(node, list):
        for i, item in enumerate(node):
            scan_commercial(item, deal_id, f"{path}[{i}]", in_cc)
    elif isinstance(node, str):
        if in_cc:
            return  # contained internal commercial context — allowed
        for w in find_external_violations(node):
            fail(f"[{deal_id}] commercial term/promise '{w}' outside commercial_context at '{path.rstrip('.')}'")


def valid_date(s):
    try:
        datetime.strptime(s, "%Y-%m-%d")
        return True
    except (ValueError, TypeError):
        return False


def check_enum(did, label, value, allowed):
    """Fail closed if a status value is outside its allowed set (case-insensitive)."""
    if value is None:
        return
    if str(value).strip().lower() not in allowed:
        fail(f"[{did}] invalid {label} status {value!r} (allowed: {sorted(allowed)})")


def extract_blocks(md_text):
    return re.findall(r"```deal-json\s*\n(.*?)```", md_text, re.DOTALL)


def validate_block(raw, idx):
    """Parse + validate a single fenced block. Returns dict or None."""
    try:
        b = json.loads(raw)
    except json.JSONDecodeError as e:
        fail(f"block #{idx + 1}: invalid JSON ({e})")
        return None

    did = b.get("deal_id", f"<block #{idx + 1}>")

    for key in REQUIRED_TOP:
        if key not in b or b[key] in (None, "", []):
            if not (key == "next_meeting"):  # next_meeting is optional
                fail(f"[{did}] required field missing/empty: '{key}'")

    if not b.get("deal_name"):
        fail(f"[{did}] deal_name missing")

    if not valid_date(b.get("last_touch", "")):
        fail(f"[{did}] last_touch missing or invalid date (YYYY-MM-DD): {b.get('last_touch')!r}")

    nba = b.get("next_best_action") or {}
    if not (isinstance(nba, dict) and nba.get("action")):
        fail(f"[{did}] next_best_action.action missing")

    # economic buyer: cannot be Confirmed without a real name/evidence
    eb = b.get("economic_buyer") or {}
    if str(eb.get("status", "")).lower() == "confirmed":
        nm = str(eb.get("name", "")).strip().lower()
        if nm in ("", "unknown"):
            fail(f"[{did}] economic_buyer marked Confirmed without a real name")

    # MEDDPICC structure + green_count reconciliation
    medd = b.get("meddpicc") or {}
    comps = medd.get("components") or {}
    for mk in MEDD_KEYS:
        if mk not in comps or "status" not in (comps.get(mk) or {}):
            fail(f"[{did}] meddpicc component missing/invalid: '{mk}'")
        else:
            check_enum(did, f"meddpicc.{mk}", comps[mk]["status"], MEDD_STATUS)
    greens = sum(1 for mk in MEDD_KEYS
                 if str((comps.get(mk) or {}).get("status", "")).lower() == "green")
    if "green_count" not in medd:
        fail(f"[{did}] meddpicc.green_count missing")
    elif medd["green_count"] != greens:
        fail(f"[{did}] meddpicc.green_count={medd['green_count']} but {greens} components are Green")

    if b.get("needs_attention") and not (b.get("attention") or {}).get("why_now"):
        fail(f"[{did}] needs_attention=true but attention.why_now missing")
    if "needs_attention" in b and not isinstance(b["needs_attention"], bool):
        fail(f"[{did}] needs_attention must be boolean, got {type(b['needs_attention']).__name__}")

    # status enum validation (fail-closed on any unsupported value)
    dm = b.get("decision_maker") or {}
    check_enum(did, "decision_maker", dm.get("status"), PERSON_STATUS)
    if dm.get("status_color"):
        check_enum(did, "decision_maker.status_color", dm.get("status_color"), COLOR_STATUS)
    check_enum(did, "economic_buyer", eb.get("status"), PERSON_STATUS)
    for i, mem in enumerate(b.get("buying_committee") or []):
        check_enum(did, f"buying_committee[{i}]", mem.get("status"), COLOR_STATUS)
    nm = b.get("next_meeting")
    if isinstance(nm, dict):
        check_enum(did, "next_meeting", nm.get("status"), MEETING_STATUS)

    # commercial_context must be internal-only when present
    cc = b.get("commercial_context")
    if cc is not None:
        if not isinstance(cc, dict):
            fail(f"[{did}] commercial_context must be an object")
        elif cc.get("internal_only") is not True:
            fail(f"[{did}] commercial_context.internal_only must be true")

    # commercial scan (commercial detail allowed only inside commercial_context)
    scan_commercial(b, did)
    return b


def to_color(status):
    return STATUS_COLOR.get(str(status).lower(), "grey")


def build_deal(b):
    medd = b["meddpicc"]
    comps = medd["components"]
    nm = b.get("next_meeting")
    next_meeting = None
    if nm:
        next_meeting = {"date": nm.get("display", ""), "iso": nm.get("date", ""),
                        "title": nm.get("label", ""), "sub": nm.get("sub", "")}
    dm = b["decision_maker"]
    eb = b["economic_buyer"]
    return {
        "id": b["deal_id"],
        "name": b["deal_name"],
        "industry": b["industry"],
        "vertical": b["vertical"],
        "stage": b["stage"],
        "nextMeeting": next_meeting,
        "meddpiccSummary": f"{medd['green_count']}/8",
        "weak": medd.get("weakest", ""),
        "competitor": b["competitor"].get("display", ""),
        "competitorTags": b["competitor"].get("tags", []),
        "decisionMaker": {"text": dm.get("text", dm.get("name", "")),
                          "status": to_color(dm.get("status_color", dm.get("status", "")))},
        "economicBuyer": eb.get("display", eb.get("name", "Unknown")),
        "metrics": " · ".join(b.get("metrics", [])),
        "identifiedPain": " ".join(b.get("identified_pain", [])),
        "nextAction": {"text": b["next_best_action"]["action"],
                       "owner": b["next_best_action"].get("owner", ""),
                       "date": b["next_best_action"].get("due", "")},
        "lastTouch": b["last_touch"],
        "confidence": b["confidence"],
        "meddpicc": {MEDD_DISPLAY[mk]: to_color(comps[mk]["status"]) for mk in MEDD_KEYS},
        "meddpiccNotes": {MEDD_DISPLAY[mk]: comps[mk]["evidence"]
                          for mk in MEDD_KEYS if comps[mk].get("evidence")},
        "committee": [{"name": m.get("name", ""), "role": m.get("role", ""),
                       "status": to_color(m.get("status", "grey")),
                       "statusText": m.get("status_text", "")}
                      for m in b.get("buying_committee", [])],
        "risks": {
            "technical": b.get("risks", {}).get("technical_security", []),
            "migration": b.get("risks", {}).get("migration_data", []),
            "decision": b.get("risks", {}).get("decision_process", []),
            "competition": b.get("risks", {}).get("competition", []),
        },
        "flags": {"securityPending": bool(b.get("flags", {}).get("security_pending", False)),
                  "migrationRisk": bool(b.get("flags", {}).get("migration_risk", False))},
        "commercialContext": b.get("commercial_context"),
    }


def build_attention(blocks):
    items = []
    for b in blocks:
        if b.get("needs_attention"):
            a = b.get("attention", {})
            items.append({"deal": b["deal_name"], "whyNow": a.get("why_now", ""),
                          "outcome": a.get("desired_outcome", ""),
                          "openQuestion": a.get("open_question", ""),
                          "owner": a.get("owner", ""), "date": a.get("due", ""),
                          "_priority": a.get("priority", 999)})
    items.sort(key=lambda x: x["_priority"])
    for x in items:
        x.pop("_priority", None)
    return items


def main():
    if not os.path.exists(SOURCE_MD):
        print(f"FATAL: source not found: {SOURCE_MD}")
        sys.exit(2)

    md = open(SOURCE_MD, encoding="utf-8").read()
    raw_blocks = extract_blocks(md)
    print(f"Found {len(raw_blocks)} deal-json block(s) in {os.path.basename(SOURCE_MD)}")
    if not raw_blocks:
        print("FATAL: no deal-json blocks found.")
        sys.exit(2)

    blocks = []
    seen_ids = set()
    for i, raw in enumerate(raw_blocks):
        b = validate_block(raw, i)
        if b is None:
            continue
        did = b.get("deal_id")
        if did in seen_ids:
            fail(f"duplicate deal_id: '{did}'")
        seen_ids.add(did)
        blocks.append(b)

    if errors:
        print("\nVALIDATION FAILED — writing nothing. Issues:")
        for e in errors:
            print(f"  - {e}")
        sys.exit(1)

    deals = [build_deal(b) for b in blocks]
    attention = build_attention(blocks)

    # record-count + set-equality reconciliation
    if len(deals) != len(raw_blocks):
        print("FATAL: deal count does not match number of fenced blocks.")
        sys.exit(1)
    block_ids = {b["deal_id"] for b in blocks}
    gen_ids = {d["id"] for d in deals}
    if block_ids != gen_ids:
        print(f"FATAL: generated deals {gen_ids} do not match block ids {block_ids}.")
        sys.exit(1)

    data = {
        "meta": {
            "source_file": "deal_command_center_v1.md",
            "generated_at": GENERATED_AT,
            "command_center_as_of": COMMAND_CENTER_AS_OF,
            "record_count": len(deals),
            "stale_days": STALE_DAYS,
            "excluded_fields_notice": EXCLUDED_FIELDS_NOTICE,
            "governance_notice": GOVERNANCE_NOTICE,
        },
        "attention": attention,
        "deals": deals,
    }

    # final safety: scan the assembled data too (exempting notice keys)
    scan_commercial(data, "GENERATED")
    if errors:
        print("\nVALIDATION FAILED on generated data — writing nothing. Issues:")
        for e in errors:
            print(f"  - {e}")
        sys.exit(1)

    header = (
        "/* =====================================================================\n"
        "   deal_dashboard_data_v1.js\n"
        "   GENERATED FILE — do not edit by hand.\n"
        "   Produced by refresh_deal_dashboard_data_v1.py from the approved\n"
        "   deal-json blocks in deal_command_center_v1.md (the source of truth).\n"
        "   If this file and the Command Center disagree, the Command Center wins.\n"
        "===================================================================== */\n"
    )
    body = "window.DEAL_DASHBOARD_DATA = " + json.dumps(data, indent=2, ensure_ascii=False) + ";\n"
    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write(header + body)

    print("VALIDATION PASSED.")
    print(f"Wrote {os.path.basename(OUTPUT_JS)} — record_count={len(deals)}, attention={len(attention)}")
    for d in deals:
        g = sum(1 for v in d["meddpicc"].values() if v == "green")
        print(f"  - {d['name']}: {d['meddpiccSummary']} (greens={g}), last_touch={d['lastTouch']}, "
              f"meeting={d['nextMeeting']['date'] if d['nextMeeting'] else 'none'}")


if __name__ == "__main__":
    main()
